################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctions.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q7.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q31.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f16.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f32.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f64.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q15.c \
../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctions.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q7.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q31.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f16.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f32.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f64.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q15.o \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctions.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q7.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q31.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f16.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f32.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f64.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q15.d \
./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CMSIS-DSP-1.18.0/Source/StatisticsFunctions/%.o CMSIS-DSP-1.18.0/Source/StatisticsFunctions/%.su CMSIS-DSP-1.18.0/Source/StatisticsFunctions/%.cyclo: ../CMSIS-DSP-1.18.0/Source/StatisticsFunctions/%.c CMSIS-DSP-1.18.0/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I"C:/Users/karthikeyan m/STM32CubeIDE/workspace_1.19.0/DISC-ADC/Drivers/CMSIS-DSP-1.18.0/Include" -I"C:/Users/karthikeyan m/STM32CubeIDE/workspace_1.19.0/DISC-ADC/Drivers/CMSIS-DSP-1.18.0/PrivateInclude" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../PDM2PCM/App -I../Middlewares/ST/STM32_Audio/Addons/PDM/Inc -I"C:/Users/karthikeyan m/STM32CubeIDE/workspace_1.19.0/DISC-ADC/CMSIS-DSP-1.18.0/Include" -I"C:/Users/karthikeyan m/STM32CubeIDE/workspace_1.19.0/DISC-ADC/CMSIS-DSP-1.18.0/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-CMSIS-2d-DSP-2d-1-2e-18-2e-0-2f-Source-2f-StatisticsFunctions

clean-CMSIS-2d-DSP-2d-1-2e-18-2e-0-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctions.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctions.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctions.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmax_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o
	-$(RM) ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_absmin_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_accumulate_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_entropy_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_logsumexp_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f32.o
	-$(RM) ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_max_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mean_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q15.su
	-$(RM) ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_min_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_mse_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q7.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q7.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q7.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_power_q7.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_rms_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f32.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_std_q31.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f16.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f16.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f16.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f16.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f32.cyclo
	-$(RM) ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f32.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f32.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f32.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f64.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f64.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f64.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_f64.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q15.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q15.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q15.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q15.su ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q31.cyclo ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q31.d ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q31.o ./CMSIS-DSP-1.18.0/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-CMSIS-2d-DSP-2d-1-2e-18-2e-0-2f-Source-2f-StatisticsFunctions

